"""Initial migration

Revision ID: 60ef9ed47f17
Revises: 
Create Date: 2024-10-06 17:12:32.440362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ef9ed47f17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('statement_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_id'), 'statement', ['id'], unique=False)
    op.create_table('statement_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_debit', sa.Float(), nullable=True),
    sa.Column('total_credit', sa.Float(), nullable=True),
    sa.Column('no_debit', sa.Integer(), nullable=True),
    sa.Column('no_credit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_details_id'), 'statement_details', ['id'], unique=False)
    op.create_table('statement_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_transactions_id'), 'statement_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_transactions_id'), table_name='statement_transactions')
    op.drop_table('statement_transactions')
    op.drop_index(op.f('ix_statement_details_id'), table_name='statement_details')
    op.drop_table('statement_details')
    op.drop_index(op.f('ix_statement_id'), table_name='statement')
    op.drop_table('statement')
    # ### end Alembic commands ###
