"""Add amount column

Revision ID: 99217962edba
Revises: 60ef9ed47f17
Create Date: 2024-10-06 17:39:28.060703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99217962edba'
down_revision: Union[str, None] = '60ef9ed47f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'statement_details', ['statement_id'])
    op.add_column('statement_transactions', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement_transactions', 'amount')
    op.drop_constraint(None, 'statement_details', type_='unique')
    # ### end Alembic commands ###
